name = "Hyde"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "Thoughts on Swift and other good stuff by Jeff Blagdon"
tags = ["blog", "swift", "programming", "ios", "xcode", "objective-c", "functional", "reactive"]
features = ["blog", "themes", "disqus"]
min_version = 0.14

[author]
    name = "spf13"
    homepage = "http://spf13.com"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"